sudo: required
services:
  - docker
language: node_js
node_js:
  - 8

script:
  - docker build -t tsmean-spinner -f ./docker/travis.dockerfile .
  - docker run tsmean-spinner npm test

branches:
  only:
    - "master"
